export const ActionTypes = {
    SET_TOKEN : "SET_TOKEN",
    DELETE_TOKEN : "DELETE_TOKEN",
    SET_LOADING : "SET_LOADING",
    SET_BOOK_LIST: "SET_BOOK_LIST",
    SET_DELEVERED_STATUS: "SET_DELEVERED_STATUS"
}